#!/bin/bash
set -euo pipefail
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
. "$DIR/project-profile"

episode_name
"${dvddecrypter}" /MODE IFO /SRC I: /DEST "${project_dir}" /VTS 3 /PGC 1 /SPLIT NONE /START /CLOSE