#!/bin/bash
set -euo pipefail
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
. "$DIR/project-profile"

  echo "path ${source_root}"
read -p "Delete project '${root_filename}' Are you sure? " -n 1 -r confirm
echo

if [[ ! "$confirm" =~ ^[Yy]$ ]]; then
  echo "Aborting."
  exit 1
fi

node $DIR/../js/delete-files.js "$source_root" "$image_dir"
